### ISSUE TITLE
Ensure that Executor can only ever be delegatecalled

### ISSUE THREAD

**Issue by mattdf** [weiroll/weiroll#27]
If Executor is directly called without delegatecall, an operation it calls out to could call selfdestruct() and destroy the executor contract.

A guard has to be built in via a code-stored immutable var that holds the deployed contract address and checks `address(this) != self` prior to running any commands.

**Comment by decanus** [comment]
@mattdf i think there may be some value in splitting this, either having one you can call internally or one you delegatecall. delegatecalling adds gas, if you can justify redeploying the executor through an abstraction you should be able to.

**Comment by mattdf** [comment]
How much gas does it add compared to a normal call? And does having that split make maintaining the other libs more burdensome? (both on the planner side and on the solidity command lib side)

I feel that if we allow it but always just dev assuming delegatecall is the only scenario, weird edge cases might creep in over time.

**Comment by decanus** [comment]
hmm, i don't think it will make much difference, we make the executor abstract and then have one implemented that just calls the internal function as the one that cna only be delegatecalled.
